INSERT INTO "consent_items"
  ("key", "version", "locale", "title", "body", "is_required", "is_active")
VALUES
  ('terms', '2026-04-28', 'ko', '이용약관', 'Grabit 서비스 이용 약관 및 회원 권리와 의무에 동의합니다.', true, true),
  ('privacy', '2026-04-28', 'ko', '개인정보처리방침', 'Grabit 개인정보 처리방침에 따른 개인정보 처리에 동의합니다.', true, true),
  ('pipa_required', '2026-04-28', 'ko', '개인정보 필수 수집 및 이용', '회원 가입, 본인 확인, 예매 처리를 위한 필수 개인정보 수집 및 이용에 동의합니다.', true, true),
  ('cross_border_transfer', '2026-04-28', 'ko', '개인정보 국외이전', '서비스 제공을 위한 개인정보 국외이전에 동의합니다.', true, true),
  ('pdpa_notice', '2026-04-28', 'ko', '태국 PDPA 고지', '태국 이용자를 위한 PDPA 개인정보 처리 고지를 확인했습니다.', true, true),
  ('pipl_notice', '2026-04-28', 'ko', '중국 PIPL 고지', '중국 이용자를 위한 PIPL 개인정보 처리 고지를 확인했습니다.', true, true),
  ('marketing', '2026-04-28', 'ko', '마케팅 수신 동의', '공연, 전시, 혜택 정보 등 마케팅 메시지 수신에 동의합니다.', false, true),
  ('terms', '2026-04-28', 'en', 'Terms of Service', 'I agree to the Grabit service terms and member obligations.', true, true),
  ('privacy', '2026-04-28', 'en', 'Privacy Policy', 'I agree to Grabit processing personal data under the Privacy Policy.', true, true),
  ('pipa_required', '2026-04-28', 'en', 'Required Personal Data Collection and Use', 'I agree to required personal data collection and use for sign-up, identity verification, and booking.', true, true),
  ('cross_border_transfer', '2026-04-28', 'en', 'Cross-border Personal Data Transfer', 'I agree to cross-border personal data transfer required to provide the service.', true, true),
  ('pdpa_notice', '2026-04-28', 'en', 'Thailand PDPA Notice', 'I acknowledge the PDPA privacy notice for users in Thailand.', true, true),
  ('pipl_notice', '2026-04-28', 'en', 'China PIPL Notice', 'I acknowledge the PIPL privacy notice for users in China.', true, true),
  ('marketing', '2026-04-28', 'en', 'Marketing Consent', 'I agree to receive performance, exhibition, benefit, and other marketing messages.', false, true),
  ('terms', '2026-04-28', 'th', 'ข้อกำหนดการใช้บริการ', 'ฉันยอมรับข้อกำหนดการใช้บริการและหน้าที่ของสมาชิก Grabit', true, true),
  ('privacy', '2026-04-28', 'th', 'นโยบายความเป็นส่วนตัว', 'ฉันยอมรับการประมวลผลข้อมูลส่วนบุคคลของ Grabit ตามนโยบายความเป็นส่วนตัว', true, true),
  ('pipa_required', '2026-04-28', 'th', 'การเก็บและใช้ข้อมูลส่วนบุคคลที่จำเป็น', 'ฉันยอมรับการเก็บและใช้ข้อมูลส่วนบุคคลที่จำเป็นสำหรับการสมัคร ยืนยันตัวตน และการจอง', true, true),
  ('cross_border_transfer', '2026-04-28', 'th', 'การโอนข้อมูลส่วนบุคคลข้ามประเทศ', 'ฉันยอมรับการโอนข้อมูลส่วนบุคคลข้ามประเทศที่จำเป็นต่อการให้บริการ', true, true),
  ('pdpa_notice', '2026-04-28', 'th', 'ประกาศ PDPA ของไทย', 'ฉันรับทราบประกาศความเป็นส่วนตัวตาม PDPA สำหรับผู้ใช้ในประเทศไทย', true, true),
  ('pipl_notice', '2026-04-28', 'th', 'ประกาศ PIPL ของจีน', 'ฉันรับทราบประกาศความเป็นส่วนตัวตาม PIPL สำหรับผู้ใช้ในประเทศจีน', true, true),
  ('marketing', '2026-04-28', 'th', 'ความยินยอมทางการตลาด', 'ฉันยินยอมรับข้อความการตลาดเกี่ยวกับการแสดง นิทรรศการ และสิทธิประโยชน์', false, true),
  ('terms', '2026-04-28', 'zh-CN', '服务条款', '我同意 Grabit 服务条款及会员权利义务。', true, true),
  ('privacy', '2026-04-28', 'zh-CN', '隐私政策', '我同意 Grabit 根据隐私政策处理个人信息。', true, true),
  ('pipa_required', '2026-04-28', 'zh-CN', '必要个人信息收集和使用', '我同意为注册、身份验证和预订所必需的个人信息收集和使用。', true, true),
  ('cross_border_transfer', '2026-04-28', 'zh-CN', '个人信息跨境传输', '我同意为提供服务所必需的个人信息跨境传输。', true, true),
  ('pdpa_notice', '2026-04-28', 'zh-CN', '泰国 PDPA 通知', '我已确认面向泰国用户的 PDPA 隐私通知。', true, true),
  ('pipl_notice', '2026-04-28', 'zh-CN', '中国 PIPL 通知', '我已确认面向中国用户的 PIPL 隐私通知。', true, true),
  ('marketing', '2026-04-28', 'zh-CN', '营销接收同意', '我同意接收演出、展览、优惠等营销信息。', false, true),
  ('terms', '2026-04-28', 'zh-TW', '服務條款', '我同意 Grabit 服務條款及會員權利義務。', true, true),
  ('privacy', '2026-04-28', 'zh-TW', '隱私權政策', '我同意 Grabit 依隱私權政策處理個人資料。', true, true),
  ('pipa_required', '2026-04-28', 'zh-TW', '必要個人資料蒐集與使用', '我同意為註冊、身分驗證和預訂所必要的個人資料蒐集與使用。', true, true),
  ('cross_border_transfer', '2026-04-28', 'zh-TW', '個人資料跨境傳輸', '我同意為提供服務所必要的個人資料跨境傳輸。', true, true),
  ('pdpa_notice', '2026-04-28', 'zh-TW', '泰國 PDPA 通知', '我已確認面向泰國使用者的 PDPA 隱私通知。', true, true),
  ('pipl_notice', '2026-04-28', 'zh-TW', '中國 PIPL 通知', '我已確認面向中國使用者的 PIPL 隱私通知。', true, true),
  ('marketing', '2026-04-28', 'zh-TW', '行銷接收同意', '我同意接收演出、展覽、優惠等行銷訊息。', false, true)
ON CONFLICT ("key", "version", "locale")
DO UPDATE SET
  "title" = EXCLUDED."title",
  "body" = EXCLUDED."body",
  "is_required" = EXCLUDED."is_required",
  "is_active" = true,
  "updated_at" = now();
