/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env= --include-runtime=false` (hash: 7ff66da78aad4fe7581bb5d8f845d805)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface ProductionEnv {
		WEB_ORIGIN: "https://grabit-web-d3c6wrfdbq-du.a.run.app";
		API_ORIGIN: "https://grabit-api-d3c6wrfdbq-du.a.run.app";
		ALLOW_STAGING_HOSTS: "false";
	}
	interface Env {
		WEB_ORIGIN: "https://grabit-web-d3c6wrfdbq-du.a.run.app";
		API_ORIGIN: "https://grabit-api-d3c6wrfdbq-du.a.run.app";
		ALLOW_STAGING_HOSTS: "false" | "true";
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "WEB_ORIGIN" | "API_ORIGIN" | "ALLOW_STAGING_HOSTS">> {}
}
