/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env= --include-runtime=false` (hash: 3e715d24309cdc7ede74b4fd20419aa9)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface ProductionEnv {
		WEB_ORIGIN: "https://grabit-web-d3c6wrfdbq-du.a.run.app";
		API_ORIGIN: "https://grabit-api-d3c6wrfdbq-du.a.run.app";
	}
	interface Env {
		WEB_ORIGIN: "https://grabit-web-d3c6wrfdbq-du.a.run.app";
		API_ORIGIN: "https://grabit-api-d3c6wrfdbq-du.a.run.app";
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "WEB_ORIGIN" | "API_ORIGIN">> {}
}
