import { isForeignCheckout, type PaymentMethod, type SupportedLocale } from '@grabit/shared';

const copy = {
  ko: {
    paymentTitle: '결제 금액', ticketAmount: '티켓 금액', seatStep: '좌석 선택', paymentStep: '결제', ticketStep: '티켓', back: '좌석 선택으로',
    booker: '예매자 정보', edit: '수정', name: '이름', phone: '연락처', save: '저장', cancel: '취소', emailVerified: '이메일 인증 완료',
    nameRequired: '이름을 입력해 주세요', phoneInvalid: '국가번호를 포함한 올바른 연락처를 입력해 주세요',
    terms: '약관 동의', allTerms: '전체 동의', bookingTerms: '이용약관 및 예매·취소 규정 동의 (필수)', privacy: '개인정보 처리 안내 확인 (필수)', view: '보기', close: '확인',
    cancellationPolicy: '공연별 예매·취소 규정 확인', policyHelper: '취소 시점에 따라 수수료가 발생합니다. 해당 공연의 규정을 확인해 주세요.',
    support: '고객센터', help: '결제가 어려우신가요?', seatsCount: '티켓 {count}매', noPoster: '공연 포스터', seat: '{tierName} · {floorLabel} {row}열 {number}번',
    methodChanged: '결제수단이 변경되었습니다. 금액과 결제수단을 다시 확인해 주세요.', countryRequired: '계정 설정에서 국가를 확인한 후 다시 시도해 주세요.',
    title: '예매 내용을 확인해 주세요', performance: '공연 정보', seats: '선택 좌석',
    orderTotal: '주문 금액', serviceFee: '예매 수수료', charge: '실제 청구 금액',
    reviewCharge: '최종 청구 금액 확인', pay: '결제하기',
    chargeNotice: '화면에 표시된 통화와 금액으로 결제됩니다. 카드사의 별도 수수료는 카드사 기준을 따릅니다.',
    checking: '기존 예매를 확인하고 있어요',
    checkingBody: '결제 여부와 선택한 좌석을 확인합니다. 새 결제를 시작하지 마세요.',
    unavailable: '예매 상태를 확인하지 못했어요',
    unavailableBody: '다시 확인하거나 내 티켓에서 예매 내역을 확인해 주세요.',
    ended: '이 예매는 다시 결제할 수 없어요',
    endedBody: '예매가 종료됐거나 결제 시간이 만료됐습니다. 내 티켓에서 결과를 확인한 뒤 좌석을 다시 선택해 주세요.',
    retry: '상태 다시 확인', tickets: '내 티켓', reselect: '좌석 다시 선택',
    quoteReady: '청구 금액을 확인한 후 결제해 주세요.',
    savedMethod: '이 예매의 결제수단', foreignCard: '해외 카드', domesticCard: '국내 카드', transfer: '계좌이체',
    methodLocked: '이 예매의 결제수단이 고정되었습니다. 아래에서 같은 결제수단을 선택해 주세요.',
  },
  en: {
    paymentTitle: 'Payment summary', ticketAmount: 'Tickets', seatStep: 'Choose seats', paymentStep: 'Payment', ticketStep: 'Tickets', back: 'Back to seats',
    booker: 'Booking contact', edit: 'Edit', name: 'Name', phone: 'Phone number', save: 'Save', cancel: 'Cancel', emailVerified: 'Email verified',
    nameRequired: 'Enter your name', phoneInvalid: 'Enter a valid phone number including the country code',
    terms: 'Terms and privacy', allTerms: 'Agree to all required terms', bookingTerms: 'Terms of service and cancellation policy (required)', privacy: 'Privacy notice (required)', view: 'Read', close: 'Close',
    cancellationPolicy: 'Read this event’s booking and cancellation policy', policyHelper: 'Cancellation fees depend on when you cancel. Check the policy for this event.',
    support: 'Help centre', help: 'Need help with payment?', seatsCount: '{count} tickets', noPoster: 'Event poster', seat: '{tierName} · {floorLabel} row {row}, seat {number}',
    methodChanged: 'Your payment method changed. Review the method and amount again.', countryRequired: 'Check your country in account settings before trying again.',
    title: 'Review your booking', performance: 'Event details', seats: 'Selected seats',
    orderTotal: 'Order total', serviceFee: 'Booking fee', charge: 'Amount charged',
    reviewCharge: 'Review final charge', pay: 'Pay',
    chargeNotice: 'You will be charged in the currency and amount shown here. Your card issuer may charge separate fees.',
    checking: 'Checking your existing booking',
    checkingBody: 'We are checking your payment and seats. Please do not start another payment.',
    unavailable: 'We could not check your booking',
    unavailableBody: 'Try again or check your bookings in My tickets.',
    ended: 'This booking cannot be paid again',
    endedBody: 'The booking has ended or its payment deadline has passed. Check My tickets before choosing seats again.',
    retry: 'Check status again', tickets: 'My tickets', reselect: 'Choose seats again',
    quoteReady: 'Review the final charge before paying.',
    savedMethod: 'Payment method for this booking', foreignCard: 'International card', domesticCard: 'Korean card', transfer: 'Bank transfer',
    methodLocked: 'This booking is locked to its existing payment method. Select the same method below.',
  },
  th: {
    paymentTitle: 'สรุปยอดชำระ', ticketAmount: 'ค่าบัตร', seatStep: 'เลือกที่นั่ง', paymentStep: 'ชำระเงิน', ticketStep: 'บัตร', back: 'กลับไปเลือกที่นั่ง',
    booker: 'ข้อมูลผู้จอง', edit: 'แก้ไข', name: 'ชื่อ', phone: 'เบอร์โทรศัพท์', save: 'บันทึก', cancel: 'ยกเลิก', emailVerified: 'ยืนยันอีเมลแล้ว',
    nameRequired: 'กรุณากรอกชื่อ', phoneInvalid: 'กรุณากรอกเบอร์โทรศัพท์ที่ถูกต้องพร้อมรหัสประเทศ',
    terms: 'ข้อกำหนดและความเป็นส่วนตัว', allTerms: 'ยอมรับข้อกำหนดที่จำเป็นทั้งหมด', bookingTerms: 'ข้อกำหนดการใช้บริการและนโยบายยกเลิก (จำเป็น)', privacy: 'ประกาศความเป็นส่วนตัว (จำเป็น)', view: 'อ่าน', close: 'ปิด',
    cancellationPolicy: 'อ่านนโยบายการจองและยกเลิกของการแสดงนี้', policyHelper: 'ค่าธรรมเนียมขึ้นอยู่กับเวลาที่ยกเลิก โปรดตรวจสอบนโยบายของการแสดงนี้',
    support: 'ศูนย์ช่วยเหลือ', help: 'ต้องการความช่วยเหลือในการชำระเงิน?', seatsCount: 'บัตร {count} ใบ', noPoster: 'โปสเตอร์การแสดง', seat: '{tierName} · {floorLabel} แถว {row} ที่นั่ง {number}',
    methodChanged: 'วิธีชำระเงินเปลี่ยนไป กรุณาตรวจสอบวิธีและยอดอีกครั้ง', countryRequired: 'กรุณาตรวจสอบประเทศในการตั้งค่าบัญชีก่อนลองอีกครั้ง',
    title: 'ตรวจสอบรายละเอียดการจอง', performance: 'รายละเอียดการแสดง', seats: 'ที่นั่งที่เลือก',
    orderTotal: 'ยอดรวมการจอง', serviceFee: 'ค่าธรรมเนียมการจอง', charge: 'ยอดที่เรียกเก็บจริง',
    reviewCharge: 'ตรวจสอบยอดชำระสุดท้าย', pay: 'ชำระเงิน',
    chargeNotice: 'ระบบจะเรียกเก็บตามสกุลเงินและยอดที่แสดงบนหน้าจอ ผู้ออกบัตรอาจเรียกเก็บค่าธรรมเนียมเพิ่มเติม',
    checking: 'กำลังตรวจสอบการจองเดิม',
    checkingBody: 'กำลังตรวจสอบการชำระเงินและที่นั่ง กรุณาอย่าเริ่มชำระเงินใหม่',
    unavailable: 'ไม่สามารถตรวจสอบสถานะการจองได้',
    unavailableBody: 'ลองอีกครั้งหรือตรวจสอบการจองในบัตรของฉัน',
    ended: 'ไม่สามารถชำระเงินสำหรับการจองนี้อีกได้',
    endedBody: 'การจองสิ้นสุดลงหรือหมดเวลาชำระเงินแล้ว กรุณาตรวจสอบบัตรของฉันก่อนเลือกที่นั่งใหม่',
    retry: 'ตรวจสอบสถานะอีกครั้ง', tickets: 'บัตรของฉัน', reselect: 'เลือกที่นั่งใหม่',
    quoteReady: 'ตรวจสอบยอดเรียกเก็บสุดท้ายก่อนชำระเงิน',
    savedMethod: 'วิธีชำระเงินของการจองนี้', foreignCard: 'บัตรต่างประเทศ', domesticCard: 'บัตรเกาหลี', transfer: 'โอนผ่านธนาคาร',
    methodLocked: 'วิธีชำระเงินของการจองนี้ถูกล็อกแล้ว กรุณาเลือกวิธีเดิมด้านล่าง',
  },
  'zh-CN': {
    paymentTitle: '付款明细', ticketAmount: '票价', seatStep: '选择座位', paymentStep: '付款', ticketStep: '门票', back: '返回选座',
    booker: '预订人信息', edit: '修改', name: '姓名', phone: '联系电话', save: '保存', cancel: '取消', emailVerified: '邮箱已验证',
    nameRequired: '请输入姓名', phoneInvalid: '请输入包含国家区号的有效电话号码',
    terms: '条款与隐私', allTerms: '同意全部必需条款', bookingTerms: '服务条款及退票规则（必需）', privacy: '隐私声明（必需）', view: '查看', close: '关闭',
    cancellationPolicy: '查看此演出的预订及退票规则', policyHelper: '退票费用取决于取消时间，请查看此演出的规则。',
    support: '客服中心', help: '付款需要帮助？', seatsCount: '{count} 张票', noPoster: '演出海报', seat: '{tierName} · {floorLabel} {row}排 {number}号',
    methodChanged: '付款方式已更改，请重新确认付款方式和金额。', countryRequired: '请先在账户设置中确认所在国家。',
    title: '请确认预订信息', performance: '演出信息', seats: '已选座位',
    orderTotal: '订单金额', serviceFee: '预订手续费', charge: '实际扣款金额',
    reviewCharge: '确认最终扣款金额', pay: '付款',
    chargeNotice: '将按页面显示的币种和金额扣款。发卡行可能另收手续费。',
    checking: '正在查询原有预订',
    checkingBody: '正在确认付款和座位，请勿重复发起付款。',
    unavailable: '暂时无法确认预订状态',
    unavailableBody: '请重试，或在“我的门票”中查看预订记录。',
    ended: '此预订无法再次付款',
    endedBody: '预订已结束或付款期限已过。请先查看“我的门票”，然后重新选择座位。',
    retry: '重新查询状态', tickets: '我的门票', reselect: '重新选座',
    quoteReady: '请确认最终扣款金额后付款。',
    savedMethod: '此预订的付款方式', foreignCard: '国际银行卡', domesticCard: '韩国银行卡', transfer: '银行转账',
    methodLocked: '此预订已锁定付款方式，请在下方选择原付款方式。',
  },
} satisfies Record<SupportedLocale, Record<string, string>>;

export function getCheckoutCopy(locale: SupportedLocale) {
  return copy[locale];
}

export function getCheckoutMethodLabel(method: PaymentMethod, locale: SupportedLocale) {
  if (method.method === 'CARD') return isForeignCheckout(method) ? copy[locale].foreignCard : copy[locale].domesticCard;
  if (method.method === 'TRANSFER' || method.method === 'VIRTUAL_ACCOUNT') return copy[locale].transfer;
  return ({ ALIPAY_PLUS: 'Alipay', PAYPAL: 'PayPal', TRUEMONEY: 'TrueMoney', TOSS_PAY: 'Toss Pay', NAVER_PAY: 'Naver Pay', KAKAOPAY: 'Kakao Pay', CARD: copy[locale].domesticCard })[method.provider];
}
